# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(599, 406)
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54); \n"
"color:white;\n"
"font: 8pt \"Poppins, sans-serif\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 32))
        self.label.setStyleSheet("font: 18pt \"Poppins, sans-serif\"; \n"
"margin-top:5px;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setStyleSheet("QFrame{ \n"
"padding:4px; \n"
"font: 11pt \"Poppins, sans-serif\";\n"
"} \n"
"QLabel{  \n"
"font:15pt \"Poppins, sans-serif\";\n"
"} \n"
"QLineEdit{  \n"
"border:2px solid white; \n"
"border-radius:5px;\n"
"padding:7px; \n"
"margin-right:3px;\n"
"font: 10pt \"Poppins, sans-serif\";\n"
"} \n"
"QPushButton{  \n"
"border:2px solid white; \n"
"border-radius:5px;\n"
"padding:4px;\n"
"font: 14pt \"Poppins, sans-serif\"; \n"
"margin-right:7px;\n"
"} \n"
"QPushButton:hover{ \n"
"background-color:white; \n"
"color:black;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.search_btn = QtWidgets.QPushButton(self.frame_2)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("font:18pt \"Poppins, sans-serif\"; \n"
"margin-left:2px; \n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.location_la = QtWidgets.QLabel(self.frame_3)
        self.location_la.setObjectName("location_la")
        self.verticalLayout_3.addWidget(self.location_la)
        self.time_la = QtWidgets.QLabel(self.frame_3)
        self.time_la.setObjectName("time_la")
        self.verticalLayout_3.addWidget(self.time_la)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setStyleSheet("font: 42pt \"Poppins, sans-serif\"; \n"
"padding:2px; \n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.temp_la = QtWidgets.QLabel(self.frame_5)
        self.temp_la.setObjectName("temp_la")
        self.horizontalLayout_3.addWidget(self.temp_la)
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setStyleSheet("font: 15pt \"Poppins, sans-serif\";")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton = QtWidgets.QRadioButton(self.frame_9)
#         self.radioButton.setStyleSheet("QRadioButton::indicator:unchecked:hover {\n"
# "    alert(1)\n"
# "}")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_4.addWidget(self.radioButton, 0, QtCore.Qt.AlignRight)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_4.addWidget(self.radioButton_2, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("font: 14pt \"Poppins, sans-serif\"; \n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.humidity_la = QtWidgets.QLabel(self.frame_6)
        self.humidity_la.setObjectName("humidity_la")
        self.verticalLayout_5.addWidget(self.humidity_la, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.wind_la = QtWidgets.QLabel(self.frame_7)
        self.wind_la.setObjectName("wind_la")
        self.verticalLayout_6.addWidget(self.wind_la, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.frame_8)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.perci_la = QtWidgets.QLabel(self.frame_8)
        self.perci_la.setObjectName("perci_la")
        self.verticalLayout_7.addWidget(self.perci_la, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #self.global_var()
        self.search_btn.clicked.connect(self.global_var) 
        self.radioButton.toggled.connect(self.update)
    #scraping goes here
    def scrap(self): 
        from requests_html import HTMLSession 
        session=HTMLSession() 
        data=dict()
        query=self.lineEdit.text().strip() 
        if query!="": 
                try:
                        url=f'https://www.google.com/search?q=weather+in+{query}' 
                        out=session.get(url) 
                        temp_c=out.html.find('span#wob_tm',first=1).text 
                        data["temp_c"]=temp_c
                        time=out.html.find('div#wob_dts',first=1).text 
                        data["time"]=time 
                        temp_f=out.html.find('span#wob_ttm',first=1).text 
                        data["temp_f"]=temp_f 
                        perci=out.html.find('span#wob_pp',first=1).text
                        data["perci"]=perci 
                        humidity=out.html.find('span#wob_hm',first=1).text 
                        data["humidity"]=humidity
                        wind=out.html.find('span#wob_tws',first=1).text 
                        data["wind"]=wind
                        climate=out.html.find('span#wob_dc',first=1).text 
                        data["climate"]=climate 
                        loc=out.html.find('div#wob_loc',first=1).text  
                        data["loc"]=loc 
                        return data,1 
                except: 
                        data={} 
                        return data,0 
        else:
                data={} 
                return data,0
    def global_var(self): 
        self.scrap()
        global data
        global flag_r
        data=self.scrap()[0];flag_r=self.scrap()[1]  
        if flag_r:
                if self.radioButton.isChecked(): 
                        self.temp_la.setText(data["temp_c"]+"°C") 
                if self.radioButton_2.isChecked(): 
                        self.temp_la.setText(data["temp_f"]+"°F") 
                self.time_la.setText(data["time"]) 
                self.perci_la.setText(data["perci"]) 
                self.humidity_la.setText(data["humidity"])
                self.wind_la.setText(data["wind"]) 
                self.location_la.setText(data["loc"]) 
        else:
                self.temp_la.setText("0"+"°C")
                self.time_la.setText("") 
                self.perci_la.setText("----") 
                self.humidity_la.setText("----")
                self.wind_la.setText("----") 
                self.location_la.setText("Not Found")
                if self.radioButton.isChecked(): 
                        self.temp_la.setText("0°C") 
                if self.radioButton_2.isChecked(): 
                        self.temp_la.setText("0°F")
        return data,flag_r  
    def update(self): 
            try:
                if flag_r: 
                        if self.radioButton.isChecked(): 
                                self.temp_la.setText(data["temp_c"]+"°C") 
                        if self.radioButton_2.isChecked(): 
                                self.temp_la.setText(data["temp_f"]+"°F") 
                else: 
                        if self.radioButton.isChecked(): 
                                self.temp_la.setText("0°C") 
                        if self.radioButton_2.isChecked(): 
                                self.temp_la.setText("0°F")
            except: 
                    try:
                        if self.radioButton.isChecked(): 
                                self.temp_la.setText("0°C") 
                        if self.radioButton_2.isChecked(): 
                                self.temp_la.setText("0°F") 
                    except: 
                            pass



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Weather App"))
        self.label_2.setText(_translate("MainWindow", "Location"))
        self.search_btn.setText(_translate("MainWindow", "search"))
        self.location_la.setText(_translate("MainWindow", "-"))
        self.time_la.setText(_translate("MainWindow", "-"))
        self.temp_la.setText(_translate("MainWindow", "0°C"))
        self.radioButton.setText(_translate("MainWindow", "°C"))
        self.radioButton_2.setText(_translate("MainWindow", "°F"))
        self.label_6.setText(_translate("MainWindow", "Humidity"))
        self.humidity_la.setText(_translate("MainWindow", "----"))
        self.label_8.setText(_translate("MainWindow", "Wind"))
        self.wind_la.setText(_translate("MainWindow", "----"))
        self.label_10.setText(_translate("MainWindow", "Precipitation"))
        self.perci_la.setText(_translate("MainWindow", "----")) 



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
